export const shopCategories = [
  { value: "clothing", label: "Clothing and Apparel" },
  { value: "footwear", label: "Footwear and Shoes" },
  { value: "jewelry", label: "Jewelry and Watches" },
  { value: "accessories", label: "Accessories" },
  { value: "electronics", label: "Electronics" },
  { value: "computers_laptops", label: "Computers and Laptops" },
  { value: "mobile_tablets", label: "Mobile Phones and Tablets" },
  { value: "gaming", label: "Gaming and Consoles" },
  { value: "home_decor", label: "Home and Decor" },
  { value: "furniture", label: "Furniture" },
  { value: "kitchen_dining", label: "Kitchen and Dining" },
  { value: "garden_outdoor", label: "Garden and Outdoor" },
  { value: "tools_hardware", label: "Tools and Hardware" },
  { value: "groceries", label: "Groceries" },
  { value: "food_beverage", label: "Food and Beverages" },
  { value: "health_beauty", label: "Health and Beauty" },
  { value: "beauty_cosmetics", label: "Beauty and Cosmetics" },
  { value: "fitness_wellness", label: "Fitness and Wellness" },
  { value: "sports", label: "Sports" },
  { value: "kids", label: "Kids" },
  { value: "baby_care", label: "Baby and Maternity" },
  { value: "toys_games", label: "Toys and Games" },
  { value: "pets", label: "Pet supplies" },
  { value: "books_stationery", label: "Books and Stationery" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "art_crafts", label: "Art and Crafts" },
  { value: "musical_instruments", label: "Musical Instruments" },
  { value: "automotive", label: "Automotive" },
  { value: "bags_luggage", label: "Bags and Luggage" },
  { value: "vintage_collectibles", label: "Vintage and Collectibles" },
  { value: "digital_products", label: "Digital Products and Software" },
  { value: "industrial_scientific", label: "Industrial and Scientific" },
  { value: "services", label: "Services" },
  { value: "education", label: "Education" },
  { value: "other", label: "Other" },
];
